# This is the configuration file for the example website of the Hugo theme
# Astatine (see https://github.com/hugcis/hugo-astatine-theme).
#
# The URL from which the site will be served
baseurl = "https://sunghwanl.github.io/"
# Language used
languageCode = "en-us"
# Website title
title = "Sung-Hwan Lee"
# Theme used
theme = "hugo-astatine-theme"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
# [taxonomies]
#     category = "categories"  
#     tag = "tags"

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

# Configure main navbar links. They can have a weight to select the order.
# [[menu.main]]
#     name = "Publications"
#     url = "/publications/"
#     weight = -90

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = "Sung-Hwan Lee"
    # Author of the site
    authorName = "Sung-Hwan Lee"
    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "https://i.imgur.com/taqGbkm.jpg"
        # Add an alt description for the image
        alt = "Profile picture"

    # Optional: add a twitter handle and mastodon handle for SEO.
    # [params.twitter]
        # name = "@Jack_harkness"
    # [params.mastodon]
        # name = "@jkharkness"
        # host = "mastodon.social"
    
    # Enable link to feed in footer
    blogrss = true

    # Enable pingback and webmention via webmention.io
    # webmention = "hugocisneros.com"


# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"
